# Generated by Django 4.2.13 on 2024-06-26 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
        ('advantage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedMaterial',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Material id')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('first_paragraph', models.TextField(verbose_name='Main paragraph')),
                ('second_paragraph', models.TextField(verbose_name='Secondary paragraph')),
                ('href_postfix', models.CharField(default='/postfix', max_length=30, unique=True, verbose_name='Href postfix')),
                ('important', models.BooleanField(default=False, verbose_name='Is important')),
                ('advantages', models.ManyToManyField(to='advantage.materialadvantage', verbose_name='Material advantages')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='image.doublesidedimage', verbose_name='Preview image')),
            ],
            options={
                'verbose_name': 'Detailed material',
                'verbose_name_plural': 'Detailed materials',
                'db_table': 'materials',
            },
        ),
    ]
