# Generated by Django 4.2.13 on 2024-06-28 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('first_paragraph', models.TextField(verbose_name='Main paragraph')),
                ('second_paragraph', models.TextField(verbose_name='Secondary paragraph')),
                ('href_postfix', models.CharField(default='/postfix', max_length=30, unique=True, verbose_name='Href postfix')),
                ('important', models.BooleanField(default=False, verbose_name='Is important')),
                ('advantages', models.ManyToManyField(to='partials.materialadvantage', verbose_name='Material advantages')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partials.doublesidedimage', verbose_name='Preview image')),
            ],
            options={
                'verbose_name': 'Product material',
                'verbose_name_plural': 'Product materials',
                'db_table': 'product_materials',
            },
        ),
        migrations.CreateModel(
            name='StockProduct',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('preparation_time', models.CharField(max_length=60, verbose_name='Time to produce')),
                ('estimated_cost', models.CharField(max_length=60, verbose_name='Estimated cost')),
                ('href_postfix', models.CharField(max_length=30, unique=True, verbose_name='Href postfix')),
                ('important', models.BooleanField(default=False, verbose_name='Is important')),
                ('images', models.ManyToManyField(to='partials.doublesidedimage', verbose_name='Product images')),
                ('materials', models.ManyToManyField(to='catalogue.productmaterial', verbose_name='Product materials')),
            ],
            options={
                'verbose_name': 'Stock product',
                'verbose_name_plural': 'Stock products',
                'db_table': 'stock_products',
            },
        ),
        migrations.CreateModel(
            name='StockSection',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('paragraph', models.TextField(blank=True, null=True, verbose_name='Paragraph')),
                ('href_postfix', models.CharField(max_length=30, unique=True, verbose_name='Href postfix')),
                ('preview_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partials.doublesidedimage', verbose_name='Preview image')),
                ('products', models.ManyToManyField(to='catalogue.stockproduct', verbose_name='Section products')),
            ],
            options={
                'verbose_name': 'Stock section',
                'verbose_name_plural': 'Stock sections',
                'db_table': 'stock_sections',
            },
        ),
    ]
