# Generated by Django 4.2.13 on 2024-11-10 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partials', '0006_remove_process_title_alter_process_image_and_more'),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaterial',
            name='advantages',
            field=models.ManyToManyField(blank=True, null=True, to='partials.materialadvantage', verbose_name='Material advantages'),
        ),
        migrations.AlterField(
            model_name='productmaterial',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partials.doublesidedimage', verbose_name='Preview image'),
        ),
        migrations.AlterField(
            model_name='stockproduct',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='partials.doublesidedimage', verbose_name='Product images'),
        ),
        migrations.AlterField(
            model_name='stocksection',
            name='preview_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partials.doublesidedimage', verbose_name='Preview image'),
        ),
        migrations.AlterField(
            model_name='stocksection',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='catalogue.stockproduct', verbose_name='Section products'),
        ),
    ]
