# Generated by Django 4.2.13 on 2024-06-26 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedSection',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Section id')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('paragraph', models.TextField(blank=True, null=True, verbose_name='Paragraph')),
                ('href_postfix', models.CharField(max_length=30, unique=True, verbose_name='Href postfix')),
                ('preview_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='image.doublesidedimage', verbose_name='Preview image')),
                ('products', models.ManyToManyField(to='product.detailedproduct', verbose_name='Section products')),
            ],
            options={
                'verbose_name': 'Detailed section',
                'verbose_name_plural': 'Detailed sections',
                'db_table': 'detailed_sections',
            },
        ),
    ]
