# Generated by Django 4.2.13 on 2024-06-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedProduct',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Product id')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('preparation_time', models.CharField(max_length=60, verbose_name='Time to produce')),
                ('estimated_cost', models.CharField(max_length=60, verbose_name='Estimated cost')),
                ('href_postfix', models.CharField(max_length=30, unique=True, verbose_name='Href postfix')),
                ('is_important', models.BooleanField(default=False, verbose_name='Is important')),
                ('images', models.ManyToManyField(to='image.doublesidedimage', verbose_name='Product images')),
                ('materials', models.ManyToManyField(to='material.detailedmaterial', verbose_name='Product materials')),
            ],
            options={
                'verbose_name': 'Detailed product',
                'verbose_name_plural': 'Detailed products',
                'db_table': 'detailed_products',
            },
        ),
    ]
