# Generated by Django 4.2.13 on 2024-06-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoublesidedImage',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Image id')),
                ('verbose_name', models.CharField(max_length=63, unique=True, verbose_name='Image title')),
                ('src', models.ImageField(upload_to='assets/', verbose_name='High resolution')),
                ('alt', models.TextField(blank=True, default='', verbose_name='Alternative text')),
                ('low_src', models.ImageField(upload_to='assets/', verbose_name='Low resolution')),
            ],
            options={
                'verbose_name': 'Doublesided image',
                'verbose_name_plural': 'Doublesided images',
                'db_table': 'doublesided_images',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FirmAdvantage',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Advantage id')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('paragraph', models.TextField(verbose_name='Main paragraph')),
            ],
            options={
                'verbose_name': 'Firm advantage',
                'verbose_name_plural': 'Firm advantages',
                'db_table': 'firm_advantages',
            },
        ),
        migrations.CreateModel(
            name='MaterialAdvantage',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Advantage id')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('paragraph', models.TextField(verbose_name='Main paragraph')),
            ],
            options={
                'verbose_name': 'Firm advantage',
                'verbose_name_plural': 'Firm advantages',
                'db_table': 'material_advantages',
            },
        ),
    ]
