# Generated by Django 4.2.13 on 2024-06-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partials', '0002_alter_materialadvantage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doublesidedimage',
            name='low_src',
            field=models.ImageField(upload_to='assets/', verbose_name='Low resolution'),
        ),
        migrations.AlterField(
            model_name='doublesidedimage',
            name='src',
            field=models.ImageField(upload_to='assets/', verbose_name='High resolution'),
        ),
    ]
