# Generated by Django 4.2.13 on 2024-09-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('partials', '0003_alter_doublesidedimage_low_src_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractAdvantage',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Advantage id')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('paragraph', models.TextField(verbose_name='Main paragraph')),
                ('purpose', models.CharField(choices=[('firm', 'Firm'), ('material', 'Material')], default='firm', verbose_name='Scope')),
            ],
            options={
                'db_table': 'advantages',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Process id')),
                ('order', models.IntegerField(unique=True, verbose_name='Process order')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Process title')),
                ('paragraph', models.TextField(verbose_name='Process paragraph')),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Processes',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='FirmAdvantage',
        ),
        migrations.DeleteModel(
            name='MaterialAdvantage',
        ),
        migrations.AlterField(
            model_name='doublesidedimage',
            name='low_src',
            field=models.ImageField(editable=False, upload_to='images/', verbose_name='Low resolution'),
        ),
        migrations.CreateModel(
            name='FirmAdvantage',
            fields=[
            ],
            options={
                'verbose_name': 'Firm advantage',
                'verbose_name_plural': 'Firm advantages',
                'db_table': 'firm_advantages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('partials.abstractadvantage',),
        ),
        migrations.CreateModel(
            name='MaterialAdvantage',
            fields=[
            ],
            options={
                'verbose_name': 'Material advantage',
                'verbose_name_plural': 'Material advantages',
                'db_table': 'material_advantages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('partials.abstractadvantage',),
        ),
    ]
