# Generated by Django 4.2.13 on 2024-09-29 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partials', '0005_process_image_alter_doublesidedimage_low_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='title',
        ),
        migrations.AlterField(
            model_name='process',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partials.doublesidedimage', verbose_name='Process image'),
        ),
        migrations.AlterField(
            model_name='process',
            name='paragraph',
            field=models.TextField(max_length=255, verbose_name='Process paragraph'),
        ),
    ]
