# Generated by Django 4.2.13 on 2024-06-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoublesidedImage',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Image id')),
                ('verbose_name', models.CharField(max_length=63, unique=True, verbose_name='Image title')),
                ('src', models.ImageField(upload_to='images/', verbose_name='High resolution')),
                ('alt', models.TextField(blank=True, default='', verbose_name='Alternative text')),
                ('low_src', models.ImageField(upload_to='images/', verbose_name='Low resolution')),
            ],
            options={
                'verbose_name': 'Doublesided image',
                'verbose_name_plural': 'Doublesided images',
                'db_table': 'doublesided_images',
                'ordering': ['id'],
            },
        ),
    ]
